"""create_setting

Revision ID: 66bab391fac9
Revises: 
Create Date: 2023-10-04 15:03:39.611683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bab391fac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('microscope_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('current_region', sa.Integer(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('axis', sa.Integer(), nullable=True),
    sa.Column('auto_start_status', sa.Boolean(), nullable=True),
    sa.Column('auto_start_time', sa.DateTime(), nullable=True),
    sa.Column('cpe1_time', sa.Integer(), nullable=True),
    sa.Column('cpe2_time', sa.Integer(), nullable=True),
    sa.Column('cpe3_time', sa.Integer(), nullable=True),
    sa.Column('cpe4_time', sa.Integer(), nullable=True),
    sa.Column('is_uptodate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
