"""add_multi_region

Revision ID: 76a97f9d90eb
Revises: 66bab391fac9
Create Date: 2023-10-06 08:44:30.967472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a97f9d90eb'
down_revision = '66bab391fac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multi_region', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('multi_region')

    # ### end Alembic commands ###
